RS/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('recommend/', include('recommend.urls')),
    path('admin/', admin.site.urls),
]

recommend/urls.py
from django.urls import path
from . import views

app_name = 'recommend'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('map/<str:account>/', views.map_with_baidu, name='map'),
    path('map/<str:account>/<str:latitude>/<str:longitude>/', views.show_position, name='show_position'),
    path('map/<str:account>/<str:latitude>/<str:longitude>/result/', views.show_result, name='show_result'),
    # path('result/', views.show_result, name='show_result'),
    # path('logout/', views.log_out, name='log_out'),
]

recommend/models.py
from django.db import models
# from django.contrib.auth.models import User


class MyUser(models.Model):
    user_name = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    L = models.CharField(max_length=1000)
    S = models.CharField(max_length=1000)

    def __str__(self):
        return self.user_name


class MyItem(models.Model):
    item_id = models.IntegerField(default=0)
    item_name = models.CharField(max_length=200)
    latitude = models.FloatField()
    longitude = models.FloatField()

recommend/views.py
from django.shortcuts import render
# from django.contrib.auth.models import User
# import django.contrib.auth as auth
from .models import MyUser, MyItem
from django.http import HttpResponse, Http404, HttpResponseRedirect
from recommend.RecommendModel import RecommendModel
import random
import json

recommend_model = RecommendModel()
with open('data/cold_start_user.txt', 'r', encoding='UTF-8') as f:
    cold_dict = eval(f.read())
with open('data/user_set.txt', 'r', encoding='UTF-8') as f:
    user_set = eval(f.read())
# item_list = list(MyUser.objects.all.values_list(('latitude', 'longitude'), flat=True))
# print(item_list)

def login(request):
    errors = []
    account = None
    password = None
    if request.method == 'POST':
        if not request.POST.get('account'):
            errors.append('Please Enter account')
        else:
            account = request.POST.get('account')
        if not request.POST.get('password'):
            errors.append('Please Enter password')
        else:
            password = request.POST.get('password')
        if account is not None and password is not None:
            # user = auth.authenticate(username=account, password=password)
            user_list = list(MyUser.objects.filter(user_name=account, password=password)
                             .values_list('user_name', flat=True))
            if user_list:
                # if user.is_active:
                #     auth.login(request, user)
                #     return HttpResponseRedirect('/index/')
                # else:
                #     errors.append('disabled account')
                return HttpResponseRedirect('/recommend/map/' + account + '/')
            else:
                errors.append('invalid user')
    return render(request, 'recommend/login.html', {'errors': errors})


def register(request):
    errors = []
    account = None
    password = None
    password2 = None
    flag = False

    if request.method == 'POST':
        if not request.POST.get('account'):
            errors.append('Please enter account')
        else:
            account = request.POST.get('account')
        if not request.POST.get('password'):
            errors.append('Please Enter password')
        else:
            password = request.POST.get('password')
        if not request.POST.get('password2'):
            errors.append('Please Enter password2')
        else:
            password2 = request.POST.get('password2')

        if password is not None and password2 is not None:
            if password == password2:
                flag = True
            else:
                errors.append('password2 is diff password')

        if account is not None and password is not None and password2 is not None and flag:
            user_list = list(MyUser.objects.filter(user_name=account, password=password)
                             .values_list('user_name', flat=True))
            if not user_list:
                MyUser.objects.create(user_name=account, password=password, L=[], S=[])
                return HttpResponseRedirect('/recommend/login/')
            else:
                errors.append('user exists')

    return render(request, 'recommend/register.html', {'errors': errors})


def map_with_baidu(request, account):
    return render(request, 'recommend/BaiduMap.html', {'account': account})


last_item_list = []
def show_position(request, account, latitude, longitude):
    user = MyUser.objects.get(user_name=account)
    L = eval(user.L)
    S = eval(user.S)
    if L.__len__() + S.__len__() == 0:
        if user.user_name in cold_dict:
            friend_list = cold_dict[user.user_name]
            flag = False
            for i in range(50):
                friend = str(random.choice(friend_list))
                if friend in user_set:
                    user_friend = list(MyUser.objects.filter(user_name=friend)
                                     .values_list('user_name', flat=True))
                    if user_friend:
                        user = MyUser.objects.get(user_name=user_friend[0])
                        user_id = user_set.index(user.user_name)
                        L = eval(user.L)
                        S = eval(user.S)
                        flag = True
                        break
                else:
                    print('friend not in user_set')
            if not flag:
                return HttpResponse('Friends not in database.')
        else:
            return HttpResponse('No friendship info.')
    else:
        user_id = user_set.index(user.user_name)
    rank_list = recommend_model.get_result(user_id, L, S, latitude, longitude)
    item_list = []
    for item_id in rank_list:
        item = MyItem.objects.get(item_id=item_id)
        item_list.append(item)
    global last_item_list
    last_item_list = item_list
    return render(request, 'recommend/Result.html', {'item_list': item_list,
                                                     'account': account,
                                                     'latitude': latitude,
                                                     'longitude': longitude})

    #     # item_list = []
    #     # for item_id in rank_list:
    #     #     name = list(MyItem.objects.filter(item_id=item_id)
    #     #                      .values_list('item_name', flat=True))[0]
    #     #     la = list(MyItem.objects.filter(item_id=item_id)
    #     #                       .values_list('latitude', flat=True))[0]
    #     #     lo = list(MyItem.objects.filter(item_id=item_id)
    #     #                       .values_list('longitude', flat=True))[0]
    #     #     item_list.append((name, float(la), float(lo)))
    #     # print(item_list)
    #     # return render(request, 'recommend/ResultMap.html', {'item_list': item_list})
    #
    #     # name_list, la_list, lo_list = [], [], []
    #     # for item_id in rank_list:
    #     #     name_list += list(MyItem.objects.filter(item_id=item_id)
    #     #                      .values_list('item_name', flat=True))
    #     #     la_list += list(MyItem.objects.filter(item_id=item_id)
    #     #                       .values_list('latitude', flat=True))
    #     #     lo_list += list(MyItem.objects.filter(item_id=item_id)
    #     #                       .values_list('longitude', flat=True))
    #     # return render(request, 'recommend/ResultMap.html', {'name_list': name_list,
    #                                                     'la_list': la_list,
    #                                                     'lo_list': lo_list,
    #                                                     'len': name_list.__len__()})


def show_result(request, account, latitude, longitude):
    name_list, la_list, lo_list = [], [], []
    for item in last_item_list:
        # item = MyItem.objects.get(item_id=item_id)
        name_list.append(item.item_name)
        la_list.append(item.latitude)
        lo_list.append(item.longitude)

        # name_list += list(MyItem.objects.filter(item_id=item_id)
        #                  .values_list('item_name', flat=True))
        # la_list += list(MyItem.objects.filter(item_id=item_id)
        #                   .values_list('latitude', flat=True))
        # lo_list += list(MyItem.objects.filter(item_id=item_id)
        #                   .values_list('longitude', flat=True))
    return render(request, 'recommend/ResultMap.html', {'name_list': json.dumps(name_list),
                                                        'la_list': json.dumps(la_list),
                                                        'lo_list': json.dumps(lo_list),
                                                        'len': json.dumps(name_list.__len__()),
                                                        'latitude': json.dumps(latitude),
                                                        'longitude': json.dumps(longitude)})

recommend/templates/recommend/BaiduMap.html
{% load staticfiles %}
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		body, html,#allmap {width: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";min-width:300px;}
		#allmap {height:100%;}
		#a{height:90px;width: 100%;bottom:0px;background:#ccc;position:fixed;}
	</style>
	<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=ehrGNgygMwfxR6D42PQViy7tvlOOfShe"></script>
	<title>Recommend With Your Position</title>
	<link rel="stylesheet" href="{% static 'recommend/assets/css/style.css' %}">
</head>

<body>
	<div id="allmap"></div>
	<div id="a">
		<button id="confirm_btn" onclick="get()">Confirm position</button>
	</div>
</body>

</html>

<script type="text/javascript">
    let latitude;
    let longitude;

	// 百度地图API功能
	let map = new BMap.Map("allmap");
	map.centerAndZoom(new BMap.Point(-118.24, 34.05), 12);

	//开启滚轮缩放
	map.enableScrollWheelZoom();

	//开启惯性拖拽
	map.enableContinuousZoom();

	//单击获取点击的经纬度
	map.addEventListener("click",function(e){
	    latitude = e.point.lat;
	    longitude = e.point.lng;

	    //清除之前的点
	    map.clearOverlays();

	    //创建标记并显示
	    position_marker = new BMap.Marker(new BMap.Point(longitude, latitude));
	    map.addOverlay(position_marker);

	    //弹窗写出经纬度
		alert(e.point.lng + "," + e.point.lat);
	});

	//点击按钮以提交位置信息
	function get() {
	    if (latitude === undefined)
	        alert("Please choose your position on the map with a click.");
        else
            window.location.href = "{% url 'recommend:map' account %}" + latitude
                + "/" + longitude + "/";
    }
</script>

recommend/templates/recommend/Result.html
{% load staticfiles %}
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		body, html,#allmap {width: 100%;height:100%;overflow: hidden;margin:0;font-family:"微软雅黑";min-width:300px;background:#3c3b52 0%;}
		#b{width:570px;height:auto;margin:auto;padding:10px;text-align:center;border-radius: 5px;}
	</style>
	<link rel="stylesheet" href="{% static 'recommend/css3-ul-ol-list/css/normalize.css' %}">
	<link rel="stylesheet" href="{% static 'recommend/css3-ul-ol-list/css/style.css' %}" media="screen" type="text/css" />
</head>
<body style="background-image: url({% static 'recommend/assets/img/backgrounds/3.gif'%}); background-size: cover">
    <div id=b style='clear:both'>
    {#<script src="/gg_bd_ad_720x90.js" type="text/javascript"></script>#}
    {#<script src="/follow.js" type="text/javascript"></script>#}
    {% if item_list %}
        <ul class="live">
            {% for item in item_list %}
                <li>
                    <a style="color: #090004">
                        {{ item.item_name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>
            No results are available.
        </p>
    {% endif %}
    </div>
    <button style="color: #090004" id="confirm_btn" onclick="get()">Show result on the map</button>

</body>
</html>
<script>
    //点击按钮以提交位置信息
	function get() {
        window.location.href = "{% url 'recommend:show_result' account latitude longitude %}";
    }
</script>

recommend/templates/recommend/ResultMap.html
<html>

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
	<style type="text/css">
		body, html,#allmap {width: 100%;height: 100%;overflow: hidden;margin:0;font-family:"微软雅黑";}
	</style>
	<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=ehrGNgygMwfxR6D42PQViy7tvlOOfShe"></script>
	<title>Recommend With Your Position</title>
</head>

<body>
	<div id="allmap"></div>
</body>

</html>

<script type="text/javascript">
    {#let item_list = {{item_list | safe}};#}
    let name_list = {{name_list | safe}};
    let la_list = {{la_list | safe}};
    let lo_list = {{lo_list | safe}};
    let len = {{ len | safe }};
    let latitude = {{ latitude | safe }};
    let longitude = {{ longitude | safe }};

	// 百度地图API功能
	let map = new BMap.Map("allmap");
	map.centerAndZoom(new BMap.Point(-118.24, 34.05), 12);

	//开启滚轮缩放
	map.enableScrollWheelZoom();

	//开启惯性拖拽
	map.enableContinuousZoom();

    for (let i = 0; i < len; i++){
        position_marker = new BMap.Marker(new BMap.Point(lo_list[i], la_list[i]));
        mylabel = new BMap.Label(name_list[i], {offset:new BMap.Size(20,-10)});
        position_marker.setLabel(mylabel);
        map.addOverlay(position_marker);
    }

    position_marker = new BMap.Marker(new BMap.Point(longitude, latitude));
    mylabel = new BMap.Label("Your Position", {offset:new BMap.Size(20,-10)});
    position_marker.setLabel(mylabel);
    map.addOverlay(position_marker);
    position_marker.setAnimation(BMAP_ANIMATION_BOUNCE);

    {#//创建标记并显示#}
    {#{% for item in item_list %}#}
    {#    position_marker = new BMap.Marker(new BMap.Point({{ item.longitude }}, {{ item.latitude }}));#}
    {#    mylabel = new BMap.Label({{ item.item_name }});#}
    {#    position_marker.setLabel(mylabel);#}
    {#    map.addOverlay(position_marker);#}
    {#{% endfor %}#}
</script>

recommend/templates/recommend/login.html
{% load staticfiles %}
<!DOCTYPE html>

<html lang="en" class="no-js">

    <head>

        <meta charset="utf-8">
        <title>Welcome login </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
		<meta name="renderer" content="webkit">

        <!-- CSS 样式引用-->
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'recommend/assets/css/reset.css' %}">
{#        <link rel="stylesheet" href="{% static 'recommend/assets/css/supersized.css' %}">#}
        <link rel="stylesheet" href="{% static 'recommend/assets/css/style.css' %}">
    </head>

    <body style="background-image: url({% static 'recommend/assets/img/backgrounds/3.gif'%}); background-size: cover">

        <div class="page-container">
            <h1 style="color: #090004">Account Login </h1>
			{% if errors %}
				<li>
					{% for error in errors %}
					 <p style="color: red;">
						Please correct the error: {{error}} below.
					 </p>
					  {% endfor %}
				</li>
			{% endif %}
			<form action="" method="post">
				{% csrf_token %}
				<input type = 'text' placeholder="Please input account" name="account" id="uid" class="username">
				<input type = 'password' placeholder="Please input password" name="password" id="pwd" class="password">
				<button type="submit" id="btn">Login</button>
                <div class="error"><span>+</span></div>
				<br><br>
				<a href="{% url 'recommend:register' %}">register new account</a>
			</form>
        </div>

        <!-- Javascript -->
{#        <script src="{% static 'recommend/assets/js/jquery-1.8.2.min.js' %}"></script>#}
{#        <script src="{% static 'recommend/assets/js/supersized.3.2.7.min.js' %}"></script>#}
{#        <script src="{% static 'recommend/assets/js/supersized-init.js' %}"></script>#}
{#        <script src="{% static 'recommend/assets/js/scripts.js' %}"></script>#}
		<!-- supersized-init.js控制主页背景轮播 -->
		<!-- scripts.js判断用户名及密码是否为空 -->
		<!-- style.css定义格式   及下面的小东西的链接 -->
		<!-- supersized.3.2.7.min.js背景轮播及其他图的控制 -->
</body>

</html>

recommend/templates/recommend/register.html
{% load staticfiles %}
<html lang="en" class="no-js">

    <head>

        <meta charset="utf-8">
        <title>Welcome Register New Account</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
		<meta name="renderer" content="webkit">

        <!-- CSS 样式引用-->
        <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=PT+Sans:400,700'>
        <link rel="stylesheet" href="{% static 'recommend/assets/css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'recommend/assets/css/supersized.css' %}">
        <link rel="stylesheet" href="{% static 'recommend/assets/css/style.css' %}">
    </head>
<body style="background-image: url({% static 'recommend/assets/img/backgrounds/3.gif'%}); background-size: cover">

 {% if errors %}
        <li>
            {% for error in errors %}
             <p style="color: red;">
                Please correct the error: {{error}} below.
             </p>
              {% endfor %}
        </li>
    {% endif %}
<div class="page-container">
    {% csrf_token %}
    <form action="" method="post">
        {% csrf_token %}
			<input type = 'text' placeholder="Please input account" name = 'account' id="uid" class="username">
            <input type = 'password' placeholder="Please input password" name = 'password' id="pwd" class="password">
            <input type = 'password' placeholder="Please input password" name ='password2' id="pwd" class="password">
			<button type="submit" id="btn">Register</button>
            <div class="error"><span>+</span></div>
    </form>
</div>
{#		<!-- Javascript -->#}
{#        <script src="assets/js/jquery-1.8.2.min.js"></script>#}
{#        <script src="assets/js/supersized.3.2.7.min.js"></script>#}
{#        <script src="assets/js/supersized-init.js"></script>#}
{#        <script src="assets/js/scripts.js"></script>#}
		<!-- supersized-init.js控制主页背景轮播 -->
		<!-- scripts.js判断用户名及密码是否为空 -->
		<!-- style.css定义格式   及下面的小东西的链接 -->
		<!-- supersized.3.2.7.min.js背景轮播及其他图的控制 -->
</body>
</html>